heat_template_version: 2015-04-30

description: Configure hieradata for Nuage configuration on the Compute

# Specify input parameters that have to be provided while
# instantiating the template.
parameters:
  server:
    description: ID of the compute node to apply this config to
    type: string

  # Config specific parameters, to be provided via parameter_defaults
  NuageActiveController:
    description: IP address of the Virtualized Services Controller (VSC)
    type: string
    default: '0.0.0.0'
  NuageMetadataPort:
    description: TCP Port to listen for metadata server requests
    type: string
    default: '9697'
  NuageNovaMetadataIp:
    description: IP address used by Nova metadata server
    type: string
    default: '0.0.0.0'
  NuageNovaMetadataPort:
    description: TCP Port used by Nova metadata server
    type: string
    default: '8775'
  NuageMetadataProxySharedSecret:
    description: Shared secret to sign the instance-id request
    type: string
    default: 'test'
  NuageNovaClientVersion:
    description: Client Version Nova
    type: string
    default: '2'
  NuageNovaOsUsername:
    description: Nova username in keystone_authtoken
    type: string
    default: 'user'
  NuageNovaOsPassword:
    description: Nova password in keystone_authtoken
    type: string
    default: 'pass'
  NuageNovaOsTennantName:
    description: Nova tenant_name in keystone_authtoken
    type: string
    default: 'user'
  NuageNovaOsAuthUrl:
    description: Nova authentication_url in keystone_authtoken
    type: string
    default: 'http://<url-here>:5000/v2.0'
  NuageMetadataAgentStartWithOvs:
    description: Set to True if nuage-metadata-agent needs to be started with nuage-openvswitch-switch
    type: string
    default: 'false'
  NuageNovaApiEndpoint:
    description: One of publicURL, internalURL, adminURL in "keystone endpoint-list"
    type: string
    default: 'publicURL'
  NuageNovaRegionName:
    description: Region name in "keystone endpoint-list"
    type: string
    default: 'RegionOne'

# Declaration of resources for the template.
# At least one resource should be defined.
resources:
  NovaNuageConfig:
    type: OS::Heat::StructuredConfig
    properties:
      group: os-apply-config
      config:
        hiera:
          datafiles:
            nova_nuage_data:
              mapped_data:
               nuage::vrs::active_controller: {get_input: ActiveController}
               nuage::metadataagent::metadata_port: {get_input: MetadataPort}
               nuage::metadataagent::nova_metadata_port: {get_input: NovaMetadataPort}
               nuage::metadataagent::metadata_secret: {get_input: SharedSecret}
               nuage::metadataagent::nova_client_version: {get_input: NovaClientVersion}
               nuage::metadataagent::nova_os_username: {get_input: NovaOsUsername}
               nuage::metadataagent::metadata_agent_start_with_ovs: {get_input: MetadataAgentStartWithOvs}
               nuage::metadataagent::nova_api_endpoint_type: {get_input: NovaApiEndpointType}
               nuage::metadataagent::nova_region_name: {get_input: NovaRegionName}

  NovaNuageDeployment:
    type: OS::Heat::StructuredDeployment
    properties:
      config: {get_resource: NovaNuageConfig}
      server: {get_param: server}
      input_values: # Values that can be specified later
        ActiveController: {get_param: NuageActiveController}
        MetadataPort: {get_param: NuageMetadataPort}
        NovaMetadataPort: {get_param: NuageNovaMetadataPort}
        SharedSecret: {get_param: NuageMetadataProxySharedSecret}
        NovaClientVersion: {get_param: NuageNovaClientVersion}
        NovaOsUsername: {get_param: NuageNovaOsUsername}
        MetadataAgentStartWithOvs: {get_param: NuageMetadataAgentStartWithOvs}
        NovaApiEndpointType: {get_param: NuageNovaApiEndpoint}
        NovaRegionName: {get_param: NuageNovaRegionName}

# Specify output parameters that will be available
# after the template is instantiated.
outputs:
  deploy_stdout:
    description: Deployment reference, used to trigger puppet apply on changes
    value: {get_attr: [NovaNuageDeployment, deploy_stdout]}
