# A Heat environment file which can be used to enable
# Nuage backend on the compute, configured via puppet
resource_registry:
  OS::TripleO::ComputeExtraConfigPre: ../puppet/extraconfig/pre_deploy/compute/nova-nuage.yaml

parameter_defaults:
  NuageActiveController: '192.0.2.120'
  NuageStandbyController: '0.0.0.0'
  NuageSriovInterfaceNames: 'eno2,eno3'
  NuageNumberOfVFs: 7
  NuageNovaComputePCIPassthroughWhitelist: "'[{\"devname\":\"eno2\",\"physical_network\":\"physnet1\"},{\"devname\":\"eno3\",\"physical_network\":\"physnet2\"}]'"
  NuageNeutronAgentsML2PhysicalDeviceMappings: 'physnet1:eno2, physnet2:eno3'
  NuageNeutronAgentsML2FirewallDriver: 'neutron.agent.firewall.NoopFirewallDriver'
